travis:
  secure:
    BINSTAR_TOKEN: YOPROidmUtGkVLy+SGFValdPFXitBFpvKIlh+xFmOaCvF8pNDweUAxJhaMhWKBtLJ6fBzp1Uw3yDBsjil6LFuLv87algVx5HFXqI6Hu6YtCvQh9w5UGGSNPN+eaDd0isdNHVZtwdjzsBIGrXNl3cdNkw0YmAxwZjdNhsg1p0vkF+MYe/WpR2nQT4tHKOnyk7gmxwt1+Smy8Vp1VqApXrocQjBoOB2L2aDddFvbIjJIhcRCDUROCEj+hI/bjL//oDLBt5Q8a3La5u1qerDdkhc2+bVsB9GB2N8xvkaHCfW5k7DqeaJhgz82QCVmFwDYmwfUXlB5podpBk9SyyeTBlk4/PFwy14plwjnX7qJv8a1LzQVFW5w8/9mIvASA+19pSbp36hpt2rrRmqRE0ZYIJtXG2LjlrZd5d6UTQLnfiv+8sVQFAkmnXv5IEXHRZmNu+4p8PnHk6mgXWJ/orYZuM/Y+N9wDip0yhgWdVAmeNnaDsRPiRF1DyO00GCei1LNUWkTrtZaIMc6r6gW7q3dxYNBpo/XJTfN2yvMrZKE+sWtDWUdaNLEKTLVU4r354X0zX/Y2AoHrLjqvd473CnfzTVPgWtPP+P/rZJUv3xnU+cS7QkaXiZ3gGV+AopJpp9LF7Y0eeFOBH2S2HgFm4aUr4wQKv9s9c5MCvW6wt/mNzJr4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
